# -------------------------------------------------------------------
# Fichier : ~/.config/starship.toml
# Rôle   : Configuration du prompt Starship avec palette Tokyo Night
# -------------------------------------------------------------------

palette = "tokyo-night"

format = """                      
$username$hostname $directory $git_branch$git_status
$cmd_duration
$character
"""

[username]
show_always = true
style_user = "bold green"
style_root = "bold red"
format = "[$user]($style)"

[hostname]
ssh_only = false
format = "[@$hostname]($style)"
style = "bold yellow"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "cyan bold"
format = "[$path]($style) "

[git_branch]
symbol = " "         # Nécessite Hack Nerd Font
style = "bold purple"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold purple"
format = "[$all_status$ahead_behind]($style) "

[cmd_duration]
min_time = 1000
format = "took [$duration]($style)"
style = "bold blue"

[character]
success_symbol = "[➜](bold green) "
error_symbol   = "[✗](bold red) "
vicmd_symbol   = "[V](bold yellow) "
